replicaCount: 1

image:
  repository: image-registry.apps.silver.devops.gov.bc.ca/d78a41-dev/nextjs-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

route:
  enabled: true
  host: nextjs-app.apps.silver.devops.gov.bc.ca

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"
